# Generated by Django 4.2.8 on 2023-12-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='License_plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_img', models.ImageField(blank=True, null=True, unique=True, upload_to='car_imgs')),
                ('car_num', models.CharField(max_length=32, null=True, unique=True, verbose_name='车牌号')),
                ('color', models.CharField(max_length=32, verbose_name='车牌颜色')),
            ],
        ),
    ]
